matrix:
  include:
    - language: node_js
      node_js:
        - 10
      cache: npm
      before_install:
        - cd ui
      install:
        - npm install
      script:
        - npm run test
        - npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ui/build/dist


branches:
  only:
    - master

notifications:
  email: false
