matrix:
  include:
    - language: node_js
      node_js:
        - 10
      cache: npm
      before_install:
        - cd ui
      install:
        - npm install
      script:
        - npm test
        - npm build


branches:
  only:
    - master

notifications:
  email: false
